cmake_minimum_required(VERSION 3.14)
project(PR1_1)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_subdirectory(../PR1_1/lib/googletest)

include_directories(/opt/homebrew/opt/ncurses/include)
link_directories(/opt/homebrew/opt/ncurses/lib)

add_executable(PR1_1
        main.cpp
        classes/FloatRange.cpp
)

target_link_libraries(PR1_1)

add_executable(PR1_1_tests
        classes/FloatRange.cpp
        tests/tests.cpp
)

target_link_libraries(PR1_1_tests gtest gtest_main)

enable_testing()
include(GoogleTest)
gtest_discover_tests(PR1_1_tests)
